apiVersion: v2
name: velero-backup-reporter
description: Backup report generator and web UI for Velero
type: application
version: v0.3.3
appVersion: "v0.3.3"
maintainers:
  - name: MichaelTrip
    url: https://github.com/MichaelTrip
sources:
  - https://github.com/MichaelTrip/velero-backup-reporter
keywords:
  - velero
  - backup
  - kubernetes
  - monitoring
