apiVersion: v2
name: velero-backup-reporter
description: Backup report generator and web UI for Velero
type: application
version: v1.0.1
appVersion: "v1.0.1"
maintainers:
  - name: MichaelTrip
    url: https://github.com/MichaelTrip
sources:
  - https://github.com/MichaelTrip/velero-backup-reporter
keywords:
  - velero
  - backup
  - kubernetes
  - monitoring
